### ISSUE TITLE
When trying to run Elite

### ISSUE THREAD

**Issue by bhaizlett123** [cobbr/Elite#14]
When trying to run Elite to connect to covenant i keep getting the following error, can't get passed this. This error is after i put the password and the certificate hash.

[!] Unknown Exception Occured: Value cannot be null.
Parameter name: token
   at Microsoft.Rest.TokenCredentials..ctor(String token, String tokenType)
   at Elite.Elite.Login(String CovenantUsername, String CovenantPassword, String CovenantHash) in /app/Elite.cs:line 183
   at Elite.Elite.<>c__DisplayClass0_0.<Main>b__0() in /app/Elite.cs:line 91

**Comment by cobbr** [comment]
Hey @bhaizlett123, copying the README below, Elite has been deprecated and is no longer needed to use Covenant:

# Deprecated (Temporarily)

The parent [Covenant](https://github.com/cobbr/Covenant) project no longer requires a client-side application. Elite has temporarily been deprecated. Please instead use the web interface included with the Covenant project.

Elite may eventually be brought up-to-date with the Covenant project as an alternative interface, but for now this project is not updated and will not work with Covenant v0.3 or higher.

**Comment by stillbigjosh** [comment]
:(
