### ISSUE TITLE
Elite doesn't properly handle trailing spaces in variable values

### ISSUE THREAD

**Issue by dooms-401trg** [cobbr/Elite#3]
Minor issue, just noticed that in Listeners\HTTP if I try "Set ConnectAddress 192.168.10.50 " it says it's an invalid option, but "Set ConnectAddress 192.168.10.50" works fine.

**Comment by cobbr** [comment]
Easy enough fix: bce6b04b1fc197f675cc4d30e746977640833b7f

Thanks @dooms-401trg!
