### ISSUE TITLE
Some failure

### ISSUE THREAD

**Issue by LIZySARA** [cobbr/Elite#6]
When I use upload I have this error
![uplaod error](https://user-images.githubusercontent.com/22563762/53652073-47b70780-3c48-11e9-82ff-7ffb1a9fa702.png)

After the error I get more control over the agent
![after error](https://user-images.githubusercontent.com/22563762/53652409-1b4fbb00-3c49-11e9-9d63-19160d5ccffb.png)

So here below I restart the agent's infect and still no control over the new connection on the agent

![after error nothing](https://user-images.githubusercontent.com/22563762/53652496-518d3a80-3c49-11e9-94c0-c16fbde52fcc.png)

**Comment by cobbr** [comment]
Hey @LIZySARA, the `upload` task expects a file located in the `Elite\Elite\Data` folder.

There is an error where Elite can get into a bad "state" where all commands are failing, seems like you are encountering this error. The workaround is just to exit Elite and restart. This is a known error, and on my to-do list.

**Comment by LIZySARA** [comment]
@cobbr its good 
But if there is a possibility to automate that
did it directly
`Ex: Upload /root/file.exe`
as well as the download
`Ex: Downlad C: \ tmp \ file.exe`
it would be more interesting

**Comment by cobbr** [comment]
The problem is that Elite runs in a docker container, so it cannot read/write from the docker host. We "solve" this problem by using the `Data` folder as a shared folder between container and host.

There really isn't a way right now for me to allow read/write from folders outside the container.
